### ISSUE TITLE
[documentation] column order and naming

### ISSUE THREAD

**Issue by luketudge** [NGO-Algorithm-Audit/Bias_scan#1]
Two small inconsistencies that tripped me up a bit when using the tool.

The Readme says [here](https://github.com/NGO-Algorithm-Audit/Bias_scan/blob/c35e32047d22ce0234d91d6ef4d96296cb2b2d22/README.md?plain=1#L44) that column order is crucial and column names are unimportant, but the hint displayed by the web app [here](https://github.com/jfparie/AlgorithmAudit_website/blob/9e485aaf9f810005ce51e7b7aa37bed70f08bd70/layouts/shortcodes/bias_scan_upload.html#L119) suggests that specific column names are required.

The example data frame in the Readme [here](https://github.com/NGO-Algorithm-Audit/Bias_scan/blob/c35e32047d22ce0234d91d6ef4d96296cb2b2d22/README.md?plain=1#L50) shows an ordering scheme with features first and labels at the end, but the example file [here](https://github.com/NGO-Algorithm-Audit/Bias_scan/blob/c35e32047d22ce0234d91d6ef4d96296cb2b2d22/classifiers/BERT_disinformation_classifier/test_pred_BERT.csv) uses the opposite scheme, with labels first.

**Comment by jfparie** [comment]
Thanks for addressing this. The inconsistency stems from the new version release of the bias scan tool. For v1, only the order of the columns was of importance, not the naming of the columns. For v2, the reverse: only the naming of the columns is of importance, not the order of the columns. The README is aligned with the v2 practice. All dataframes with a ```pred_label``` and ```truth_label``` are digestible by the web app. Thanks again :-)

**Comment by luketudge** [comment]
Ah, got it! Thanks for the clarification.
